version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./scaie.db
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-scaie_secret_key_for_production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - AGENT_NAME=SCAI
      - AGENT_PERSONALITY=amigable, empático, profesional, persuasivo
      - AGENT_TONE=coloquial pero respetuoso
      - AGENT_GOAL=ayudar a los usuarios a entender los beneficios de SCAIE de manera natural
      - SKIP_AUTH=false
    volumes:
      - sqlite_data:/app/scaie.db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/app/static:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite_data: